version: '3'

services:
  
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  worker:
    build: ./worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq

  archive:
    build: ./archive
    volumes:
      - ./archive:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq


  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - '5000:5000'
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
